version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - ./src/resources:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: muscleApplication_db
    ports:
      - '5433:5432'

#a