version: '3'

services:
  db:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    networks:
      - muscle-nw
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: muscleApplication_db
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 3

networks:
  muscle-nw:
    driver: bridge
